spring:
  datasource:
    url: jdbc:mysql://10.2.192.31:3306/peking?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
    username: root
    password: anyrobot123
    driver-class-name: com.mysql.jdbc.Driver
  kafka:
    bootstrap-servers: 10.2.196.18:9092,10.2.196.19:9092,10.2.196.20:9092
    #bootstrap-servers: 10.2.196.18:9092
    template:
      default-topic: installbill
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer  #key-value序列化反序列化
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      # 重试次数
      retries: 3
      # 批量发送的消息数量
      batch-size: 16384
      # 32MB的批处理缓冲区，#producer可以用来缓存数据的内存大小。
      # 如果数据产生速度大于向broker发送的速度，producer会阻塞或者抛出异常，以“block.on.buffer.full”来表明。
      # 这项设置将和producer能够使用的总内存相关，但并不是一个硬性的限制，
      # 因为不是producer使用的所有内存都是用于缓存。一些额外的内存会用于压缩（如果引入压缩机制），同样还有一些用于维护请求。
      buffer-memory: 33554432


elasticsearch.host: 10.2.196.18
elasticsearch.port: 9200

hadoop.name-node: hdfs://10.2.196.18:9000
hadoop.namespace: /
